import { gameSchema, turnResolutionSchema } from "@wargame/shared";
import { randomUUID } from "node:crypto";
import { ValidationError } from "../errors/app-error.js";
import type { ResolveTurnInput, ResolveTurnResult, TurnResolutionService } from "./types.js";

function clampPercentage(value: number): number {
  return Math.max(0, Math.min(100, Math.round(value)));
}

export class StaticTurnResolutionService implements TurnResolutionService {
  constructor(private readonly now: () => string) {}

  async resolveTurn(input: ResolveTurnInput): Promise<ResolveTurnResult> {
    const { action, game, scenario } = input;
    const actingPrivateState = game.state.privateByPlayer.find(
      (state) => state.playerId === action.playerId
    );
    const actingPlayer = game.players.find((player) => player.id === action.playerId);
    const option = actingPrivateState?.availableOptions.find(
      (candidate) => candidate.id === action.optionId
    );

    if (!option || !actingPlayer) {
      throw new ValidationError(`Option ${action.optionId} is not legal for this turn.`);
    }

    const playableFactionOrder = game.players
      .map((player) => player.factionId)
      .filter((factionId): factionId is string => Boolean(factionId));
    const currentIndex = playableFactionOrder.findIndex(
      (factionId) => factionId === action.factionId
    );
    const nextFactionId =
      currentIndex >= 0
        ? playableFactionOrder[(currentIndex + 1) % playableFactionOrder.length]
        : game.currentFactionId;
    const nextTurnNumber = game.turnNumber + 1;
    const tensionDelta = option.kind === "military_signal" ? 12 : option.kind === "economic" ? 7 : 4;
    const nextWorldTension = clampPercentage(game.state.public.worldTension + tensionDelta);
    const nextOptions = scenario.choiceCatalog.filter(
      (candidate) => candidate.factionId === nextFactionId
    );
    const resolvedAt = this.now();

    const resolution = turnResolutionSchema.parse({
      id: randomUUID(),
      gameId: game.id,
      turnNumber: game.turnNumber,
      actionId: action.id,
      status: "resolved",
      appliedOptionId: option.id,
      actingFactionId: action.factionId,
      actor: {
        playerId: actingPlayer.id,
        playerName: actingPlayer.name,
        playerRole: actingPlayer.role,
        factionId: action.factionId
      },
      selectedAction: {
        optionId: option.id,
        title: option.title,
        kind: option.kind,
        recommendationPercent: option.recommendationPercent ?? null
      },
      publicSummary: `${option.title} has been executed, shifting crisis pressure into the next turn.`,
      privateSummaries: game.state.privateByPlayer
        .filter((state) => state.factionId === action.factionId)
        .map((state) => ({
          playerId: state.playerId,
          factionId: state.factionId,
          summary: `Internal assessment after ${option.title.toLowerCase()}: maintain readiness and monitor escalation indicators.`,
          tags: [option.kind, "post-action"]
        })),
      effects: [
        `option:${option.id}`,
        `world_tension:+${tensionDelta}`
      ],
      stateChanges: [
        {
          key: "worldTension",
          label: "World Tension",
          previousValue: game.state.public.worldTension,
          newValue: nextWorldTension,
          delta: nextWorldTension - game.state.public.worldTension,
          visibility: "public"
        },
        {
          key: "escalationRiskPercent",
          label: "Escalation Risk",
          previousValue: game.state.derived.escalationRiskPercent,
          newValue: clampPercentage(
            game.state.derived.escalationRiskPercent + Math.round(tensionDelta / 2)
          ),
          delta:
            clampPercentage(
              game.state.derived.escalationRiskPercent + Math.round(tensionDelta / 2)
            ) - game.state.derived.escalationRiskPercent,
          visibility: "derived"
        }
      ],
      updatedTracks: {
        ...game.state.public.visibleTracks,
        worldTension: nextWorldTension
      },
      escalated: tensionDelta >= 10,
      recommendationLabels:
        (option.recommendationPercent ?? 0) >= 60 ? ["advisor-favored"] : ["situational"],
      riskLabels:
        tensionDelta >= 10
          ? ["high-escalation-risk", "high-visibility"]
          : tensionDelta >= 7
            ? ["medium-escalation-risk"]
            : ["measured-risk"],
      llmNarrative: {
        headline: `Turn ${game.turnNumber}: ${option.title}`,
        publicSummary:
          "Placeholder narrative generated by the backend skeleton. Later versions can call the OpenAI Responses API through the turn-resolution service.",
        privateUpdates: [
          {
            factionId: action.factionId,
            summary:
              "Internal reporting suggests the action changed leverage but did not settle the crisis.",
            tags: ["placeholder", option.kind]
          }
        ],
        consequenceTags: [option.kind, tensionDelta >= 10 ? "escalatory" : "measured"],
        followupHooks: ["next-turn-options"],
        metadata: {
          source: "static-turn-resolution-service"
        }
      },
      resolvedAt,
      metadata: {
        integrationReady: "openai-responses-api"
      }
    });

    const updatedGame = gameSchema.parse({
      ...game,
      turnNumber: nextTurnNumber,
      phase: "briefing",
      currentFactionId: nextFactionId,
      state: {
        public: {
          ...game.state.public,
          turnNumber: nextTurnNumber,
          phase: "briefing",
          activeFactionId: nextFactionId,
          worldTension: nextWorldTension,
          publicNarrative: resolution.llmNarrative.publicSummary,
          headline: resolution.llmNarrative.headline,
          updatedAt: resolvedAt
        },
        privateByPlayer: game.state.privateByPlayer.map((state) => ({
          ...state,
          turnNumber: nextTurnNumber,
          privateBriefing:
            state.factionId === nextFactionId
              ? `Prepare for the next move. ${scenario.title} remains unresolved.`
              : state.factionId === action.factionId
                ? `Post-action assessment: ${option.title} increased pressure and drew fresh scrutiny.`
                : state.privateBriefing,
          intelligence:
            state.factionId === nextFactionId
              ? [
                  `Placeholder intelligence: ${nextFactionId} now faces the next decision window.`,
                  `Current world tension stands at ${nextWorldTension}%.`
                ]
              : state.intelligence,
          availableOptions:
            state.factionId === nextFactionId ? nextOptions : []
        })),
        derived: {
          ...game.state.derived,
          turnNumber: nextTurnNumber,
          actingPlayerIds: game.players
            .filter((player) => player.factionId === nextFactionId)
            .map((player) => player.id),
          legalActionIds: nextOptions.map((candidate) => candidate.id),
          recommendedActionIds: nextOptions
            .filter((candidate) => (candidate.recommendationPercent ?? 0) >= 60)
            .map((candidate) => candidate.id),
          escalationRiskPercent: clampPercentage(
            game.state.derived.escalationRiskPercent + Math.round(tensionDelta / 2)
          ),
          warnings: resolution.escalated
            ? [
                ...game.state.derived.warnings,
                "Recent action increased escalation pressure."
              ]
            : game.state.derived.warnings
        }
      },
      advisorAnswers: [],
      lastResolution: resolution,
      updatedAt: resolvedAt
    });

    return {
      updatedGame,
      resolution
    };
  }
}
