import { turnGenerationArtifactsSchema } from "@wargame/shared";
import { logInfo } from "../../logger.js";
import type {
  TurnGenerationProvider,
  TurnGenerationProviderInput
} from "../types.js";

export class MockTurnGenerationProvider implements TurnGenerationProvider {
  async generateTurnArtifacts(input: TurnGenerationProviderInput): Promise<unknown> {
    logInfo("Turn resolution provider path selected.", {
      provider: "mock",
      gameId: input.game.id,
      turnNumber: input.game.turnNumber,
      actionId: input.action.id
    });

    const { action, game, selectedOption, tensionDelta } = input;

    const payload = turnGenerationArtifactsSchema.parse({
      publicSummary: `${selectedOption.title} has been executed, shifting crisis pressure into the next turn.`,
      privateSummaries: game.state.privateByPlayer
        .filter((state) => state.factionId === action.factionId)
        .map((state) => ({
          playerId: state.playerId,
          factionId: state.factionId,
          summary: `Internal assessment after ${selectedOption.title.toLowerCase()}: maintain readiness and monitor escalation indicators.`,
          tags: [selectedOption.kind, "post-action"]
        })),
      effects: [
        `option:${selectedOption.id}`,
        `world_tension:+${tensionDelta}`
      ],
      recommendationLabels:
        (selectedOption.recommendationPercent ?? 0) >= 60
          ? ["advisor-favored"]
          : ["situational"],
      riskLabels:
        tensionDelta >= 10
          ? ["high-escalation-risk", "high-visibility"]
          : tensionDelta >= 7
            ? ["medium-escalation-risk"]
            : ["measured-risk"],
      recommendedNextOptionIds: input.nextOptions
        .filter((candidate) => (candidate.recommendationPercent ?? 0) >= 60)
        .map((candidate) => candidate.id),
      worldUpdateSuggestions: [
        {
          key: "worldTension",
          direction: tensionDelta >= 10 ? "increase" : "hold",
          magnitude: tensionDelta >= 10 ? "high" : "low",
          rationale:
            tensionDelta >= 10
              ? "The selected action is visibly escalatory."
              : "The selected action alters pressure without a dramatic public jump."
        }
      ],
      llmNarrative: {
        headline: `Turn ${game.turnNumber}: ${selectedOption.title}`,
        publicSummary:
          "Placeholder narrative generated by the mock provider. A future OpenAI-backed provider can plug in here without changing canonical state ownership.",
        privateUpdates: [
          {
            factionId: action.factionId,
            summary:
              "Internal reporting suggests the action changed leverage but did not settle the crisis.",
            tags: ["placeholder", selectedOption.kind]
          }
        ],
        consequenceTags: [
          selectedOption.kind,
          tensionDelta >= 10 ? "escalatory" : "measured"
        ],
        followupHooks: ["next-turn-options"],
        metadata: {
          provider: "mock-turn-generation"
        }
      },
      metadata: {
        provider: "mock-turn-generation"
      }
    });

    logInfo("Turn provider result resolved.", {
      providerPath: "mock",
      resultProvider: String(payload.metadata.provider ?? "unknown"),
      usedFallback: false,
      gameId: input.game.id,
      turnNumber: input.game.turnNumber,
      actionId: input.action.id
    });

    return payload;
  }
}
